apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imageprocessors.imaging.example.com
spec:
  group: imaging.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              data:
                type: string
              operation:
                type: string
              params:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required:
            - data
            - operation
          status:
            type: object
            properties:
              phase:
                type: string
              result:
                type: string
              message:
                type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Operation
      type: string
      jsonPath: .spec.operation
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: imageprocessors
    singular: imageprocessor
    kind: ImageProcessor
